language: c
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: OPAMWITHDOC=false bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
  - osx
osx_image: xcode11.2
